name: CIC Student Blogs
description: Blogs by Student Community of Cluster Innovation Centre, University of Delhi

url: http://blog.ducic.ac.in
paginate_path: "blog/page_:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Blogs Home
   url: /index.html
 - title: Cluster Innovation Centre
   url: https://ducic.ac.in
